Repository TUK-DP/backend, pull requests merged in 2024-04, with the labels that each got.

#84 [feat] birth 필드 추가
  users/migrations/0006_user_birth.py
  users/models.py
  users/serializers.py
Labels: feat

#85 [feat] 닉네임 중복확인 구현
  users/serializers.py
  users/urls.py
  users/views.py
Labels: feat

#90 그래프 데이터 가져오는 API 구현
  diary/graph.py
  diary/serializers.py
  diary/urls.py
  diary/views.py
  docker-compose-dev.yml
Labels: feat

#93 [feat] 이미지 저장 기능 구현
  diary/migrations/0007_diary_imgurl_keywords_imgurl.py
  diary/models.py
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat

#94 [feat] 주변 치매 센터 조회 API 구현
  center/__init__.py
  center/admin.py
  center/apps.py
  center/center_data.py
  center/migrations/__init__.py
  center/models.py
  center/serializers.py
  center/tests.py
  center/urls.py
  center/views.py
  config/urls.py
Labels: feat

#95 [feat] 퀴즈 문제와 답안 API 분리
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat

#106 [feat] 키워드 조회 API 구현
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat

#103 [chore] AccessToken 과 RefreshToken을 인증 받기 위한 Swagger Setting
  config/settings.py
Labels: feat, chore

#109 [feat] User 앱 리팩토링, validator 구현, User 앱 토큰 권한 설정
  config/basemodel.py
  config/settings.py
  config/urls.py
  diary/urls.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  requirements.txt
  users/migrations/0007_user_isdeleted_user_refresh_token_diagrecord.py
  users/models.py
  users/serializers.py
  users/token_handler.py
  users/token_serializer.py
  users/urls.py
  users/validator.py
  users/views.py
Labels: feat, refactor, chore

#112 [fix] 키워드 이미지 검색 not null 필터링 추가
  diary/views.py
Labels: fix
