Repository TUK-DP/backend, pull requests merged in 2024-03, with the labels that each got.

#16 Feat/12
  .gitignore
  diary/migrations/0002_sentences_keyword.py
  diary/migrations/0003_remove_diary_content_alter_sentences_diary_quizs_and_more.py
  diary/models.py
  diary/serializers.py
  diary/textrank.py
  diary/views.py
  requirements.txt
  users/serializers.py
  users/views.py
Labels: feat

#18 Feat/17
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat

#23 [chore] deploy workflow 생성
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
Labels: chore

#28 [feat] han_spell 제거 및 불용어 처리 완료
  diary/textrank.py
Labels: feat

#34 [fix] 문장 그래프를 뽑지않음으로 에러 해결
  diary/textrank.py
Labels: bug

#35 [fix] 연결된 함수 호출을 분리해서 에러 해결
  diary/serializers.py
  diary/views.py
Labels: fix

#38 [chore] develop commit들 가져오기
  .dockerignore
  .github/workflows/deploy.yml
  .github/workflows/hotfix.yml
  Dockerfile
  config/settings.py
  diary/serializers.py
  diary/textrank.py
  diary/views.py
  requirements.txt
Labels: chore

#40 [refactor] Quizs 테이블을 Questions과 Keywords로 분리
  diary/migrations/0004_keywords_questions_delete_quizs.py
  diary/models.py
  diary/serializers.py
  diary/views.py
Labels: refactor

#41 [refactor] diary/view.py 리팩토링
  config/basemodel.py
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat, refactor

#42 [fix] 퀴즈를 만들 수 없는 경우 일기만 저장하도록 구조 수정
  diary/textrank.py
  diary/views.py
Labels: fix

#45 [fix] 짧은 단어 작성시 일기 작성 안되는 오류 해결
  diary/textrank.py
  diary/views.py
Labels: fix

#47 [feat] Diay 필드에 작성일 추가
  diary/migrations/0005_diary_writedate.py
  diary/models.py
  diary/serializers.py
  diary/views.py
Labels: feat

#50 [feat] 유저 아이디와 날짜로 일기 조회 구현
  diary/serializers.py
  diary/urls.py
  diary/views.py
Labels: feat

#57 [chore] Dockerfile 정리 및 배포 docker-compose-prod, dev yml 정의
  .dockerignore
  .gitignore
  DjangoBaseImage/Dockerfile
  Dockerfile
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose.yml
  wait-for-services.sh
Labels: chore

#59 [refactor] textrank text_rank_modules 로 패키징
  diary/text_rank_modules/__init__.py
  diary/text_rank_modules/get_rank_graph.py
  diary/text_rank_modules/string_handler.py
  diary/text_rank_modules/textrank.py
  diary/textrank.py
  diary/views.py
Labels: refactor, fix

#61 [feat] [fix] graph db 연동, 개행문자가 split 안되던 문제 해결
  diary/graph.py
  diary/text_rank_modules/get_rank_graph.py
  diary/text_rank_modules/stop_words.py
  diary/text_rank_modules/string_handler.py
  diary/text_rank_modules/textrank.py
  diary/views.py
Labels: bug, feat

#64 [chore] diary, user view 에 트랜젝션 설정
  diary/serializers.py
  diary/views.py
  users/serializers.py
  users/views.py
Labels: feat, chore

#69 [chore] gunicorn 으로 api 동기 설정
  Dockerfile
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose.yml
  requirements.txt
Labels: chore

#68 [chore] 배포 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/hotfix.yml
Labels: chore

#71 [feat] s3 연동 (이미지 업로드 기능 구현)
  config/settings.py
  config/urls.py
  docker-compose-dev.yml
  image/__init__.py
  image/admin.py
  image/apps.py
  image/migrations/__init__.py
  image/models.py
  image/s3_modules/s3_handler.py
  image/serializer.py
  image/tests.py
  image/urls.py
  image/views.py
  requirements.txt
Labels: feat, chore

#74 [feat] 일기 삭제 기능 구현
  diary/serializers.py
  diary/urls.py
  diary/views.py
  docker-compose-dev.yml
Labels: feat
