Repository TUK-DP/backend, pull requests merged in 2024-06, with the labels that each got.

#134 [feat] 배경제거 로직 삭제, 이미지생성 api 완성
  image/gpt/GenerateImage.py
  image/gpt/ImageConverter.py
  image/s3_modules/s3_handler.py
  image/serializers.py
  image/urls.py
  image/validator.py
  image/views.py
  requirements.txt
Labels: feat

#132 [refactor] user 수정 patch -> put 으로 변경
  users/serializers.py
  users/validator.py
  users/views.py
Labels: refactor

#136 [feat] 기간별 일기 조회
  config/sort_options.py
  diary/serializers.py
  diary/urls.py
  diary/validator.py
  diary/views.py
Labels: feat

#141 [feat] 번역기 API 변경
  docker-compose-dev.yml
  image/gpt/GenerateImage.py
  requirements.txt
Labels: feat

#142 [feat] 특정일기 조회시 키워드별 사진 같이 조회되도록 변경
  config/urls.py
  diary/models.py
  diary/serializers.py
  diary/serialziers/__init__.py
  diary/serialziers/diary_response_serializers.py
  diary/serialziers/diray_request_serializers.py
  diary/serialziers/graph_serializers.py
  diary/serialziers/keyword_serializers.py
  diary/serialziers/quiz_serializers.py
  diary/urls/__init__.py
  diary/urls/diary_urls.py
  diary/urls/keyword_urls.py
  diary/urls/quiz_urls.py
  diary/utils/__init__.py
  diary/utils/graph/__init__.py
  diary/utils/graph/graph.py
  diary/utils/text_rank/__init__.py
  diary/utils/text_rank/get_rank_graph.py
  diary/utils/text_rank/stop_words.py
  diary/utils/text_rank/string_handler.py
  diary/utils/text_rank/textrank.py
  diary/validator.py
  diary/views.py
  diary/views/__init__.py
  diary/views/diary_query_views.py
  diary/views/diray_command_views.py
  diary/views/graph_views.py
  diary/views/keyword_views.py
  diary/views/quiz_views.py
  image/gpt/GenerateImage.py
  image/s3_modules/s3_handler.py
  image/serializers.py
  image/views.py
Labels: feat, refactor

#145 [chore] deepl apikey cicd 설정
  .github/workflows/deploy.yml
  .github/workflows/hotfix.yml
Labels: chore

#146 [refactor] diary 키워드가 없는경우 diary 그림 띄울수 있게 diary imgUrl 추가
  diary/serialziers/diary_response_serializers.py
Labels: refactor

#148 [feat] user 테스트 코드 작성 및 리팩토링
  .github/workflows/django_test.yml
  Dockerfile
  config/basemodel.py
  diary/serialziers/diary_response_serializers.py
  diary/views/diary_query_views.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-entrypoint.sh
  users/serializers/__init__.py
  users/serializers/user_check_serializers.py
  users/serializers/user_diag_serializers.py
  users/serializers/user_get_post_put_delete_serializers.py
  users/serializers/user_login_serializers.py
  users/tests.py
  users/tests/__init__.py
  users/tests/test_user_auto_login.py
  users/tests/test_user_diag.py
  users/tests/test_user_get_put_delete_views.py
  users/tests/test_user_login.py
  users/tests/test_user_sign_up.py
  users/tests/test_validator.py
  users/token_handler.py
  users/token_serializer.py
  users/urls.py
  users/views.py
  users/views/__init__.py
  users/views/user_check_views.py
  users/views/user_diag_views.py
  users/views/user_get_update_delete_views.py
  users/views/user_login_views.py
  users/views/user_sign_up_views.py
  wait-for-services.sh
Labels: feat, refactor, chore
